package server;

public enum Endpoint {
    GET_ALL_TASKS,
    ADD_TASK,
    GET_TASK_BY_ID,
    UPDATE_TASK,
    DELETE_TASK_BY_ID,
    DELETE_ALL_TASKS,
    GET_ALL_EPICS,
    ADD_EPIC,
    GET_EPIC_BY_ID,
    UPDATE_EPIC,
    DELETE_EPIC_BY_ID,
    DELETE_ALL_EPICS,
    GET_ALL_SUBTASKS,
    ADD_SUBTASK,
    GET_SUBTASK_BY_ID,
    UPDATE_SUBTASK,
    DELETE_SUBTASK_BY_ID,
    DELETE_ALL_SUBTASKS,
    GET_HISTORY,
    GET_PRIORITIZED_TASKS,
    UNKNOWN
}
